# Generated by Django 5.1.5 on 2025-02-03 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_orde_alter_product_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orde',
            new_name='Order',
        ),
    ]
